### ISSUE TITLE
missing dependency

### ISSUE THREAD

**Issue by davehun** [danielknox/lorawan_network_tester#1]
I think this needs TheThingsNetwork as a dependency but when i add it i get quite a few compile errors

> src/lorawan.cpp:40:16: error: 'class TheThingsNetwork' has no member named 'checkPersonalize'; did you mean 'personalize'?

> src/lorawan.cpp:246:29: error: 'class TheThingsNetwork' has no member named 'getFreq'
       result.freq = lorawan.getFreq()/1000000;
                             ^~~~~~~
src/lorawan.cpp:251:29: error: 'class TheThingsNetwork' has no member named 'getFreq'
       result.freq = lorawan.getFreq()/1000000;
                             ^~~~~~~

I suspect i might just have the wrong library version

**Comment by danielknox** [comment]
Apologies for the delay. It looks like you are using the original arduino-device-lib by TTN. That's missing a few functions that I need for the network tester. The README.md of this repo lists a link (https://github.com/danielknox/arduino-device-lib) for the required dependency. I've noticed that TTN has updated their library, so in the coming days I'll check through their changes and merge any useful ones into my fork.
